### ISSUE TITLE
flow completion time

### ISSUE THREAD

**Issue by lingyuhaunti** [mkheirkhah/mmptcp#1]
Hello, I am a postgraduate students in China, and I am interested in your mmptcp, I want to better understanding it by your code, but I don't know your method that test the flow complete time, please, I want to know how to achieve it in your code, thank you.

**Comment by mkheirkhah** [comment]
There are several ways you can get flow completion times from your simulations...
Have you looked at the example folder yet?

I will close this because it is not an issue of this codebase.
